// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package queryapi

import (
	"time"
)

type Asset struct {
	UID        string         `json:"uid"`
	Type       string         `json:"type"`
	Value      string         `json:"value"`
	Attributes map[string]any `json:"attributes"`
	Confidence float64        `json:"confidence"`
	Status     string         `json:"status"`
	FirstSeen  time.Time      `json:"firstSeen"`
	LastSeen   time.Time      `json:"lastSeen"`
	RoeID      string         `json:"roeId"`
}

type AssetConnection struct {
	Nodes    []*Asset  `json:"nodes"`
	PageInfo *PageInfo `json:"pageInfo"`
}

type AssetFilter struct {
	Types       []string `json:"types,omitempty"`
	Statuses    []string `json:"statuses,omitempty"`
	ValuePrefix *string  `json:"valuePrefix,omitempty"`
	// last_seen >= seenSince
	SeenSince *time.Time `json:"seenSince,omitempty"`
}

type AssetNeighborhood struct {
	Root   *Asset   `json:"root"`
	Assets []*Asset `json:"assets"`
	Edges  []*Edge  `json:"edges"`
}

type Edge struct {
	EdgeID     string         `json:"edgeId"`
	Src        string         `json:"src"`
	Dst        string         `json:"dst"`
	Rel        string         `json:"rel"`
	Attributes map[string]any `json:"attributes"`
	FirstSeen  time.Time      `json:"firstSeen"`
	LastSeen   time.Time      `json:"lastSeen"`
}

type Finding struct {
	FindingID   string         `json:"findingId"`
	AssetUID    string         `json:"assetUid"`
	Module      string         `json:"module"`
	CheckID     string         `json:"checkId"`
	Title       string         `json:"title"`
	Severity    string         `json:"severity"`
	State       string         `json:"state"`
	Fingerprint *string        `json:"fingerprint,omitempty"`
	Validation  map[string]any `json:"validation"`
	Risk        map[string]any `json:"risk"`
	// s3:// evidence reference — masked for viewer-role callers on sensitive findings.
	EvidenceRef *string        `json:"evidenceRef,omitempty"`
	Occurrence  int            `json:"occurrence"`
	FirstSeen   time.Time      `json:"firstSeen"`
	LastSeen    time.Time      `json:"lastSeen"`
	TaskID      *string        `json:"taskId,omitempty"`
	Compliance  map[string]any `json:"compliance,omitempty"`
	LegalHold   bool           `json:"legalHold"`
	Sensitive   bool           `json:"sensitive"`
	CreatedAt   time.Time      `json:"createdAt"`
	UpdatedAt   time.Time      `json:"updatedAt"`
	// Lifecycle history (doc 04 §7.3 transitions, persisted by 09).
	Transitions []*StateTransition `json:"transitions"`
}

type FindingConnection struct {
	Nodes    []*Finding `json:"nodes"`
	PageInfo *PageInfo  `json:"pageInfo"`
}

type FindingFilter struct {
	Modules       []string `json:"modules,omitempty"`
	Severities    []string `json:"severities,omitempty"`
	States        []string `json:"states,omitempty"`
	AssetUID      *string  `json:"assetUid,omitempty"`
	TaskID        *string  `json:"taskId,omitempty"`
	CheckIDPrefix *string  `json:"checkIdPrefix,omitempty"`
	// last_seen >= seenSince
	SeenSince *time.Time `json:"seenSince,omitempty"`
}

type PageInfo struct {
	HasNextPage bool    `json:"hasNextPage"`
	EndCursor   *string `json:"endCursor,omitempty"`
	// Total rows matching the filter inside this tenant.
	TotalCount int `json:"totalCount"`
}

type Query struct {
}

type StateTransition struct {
	FromState *string        `json:"fromState,omitempty"`
	ToState   string         `json:"toState"`
	Actor     map[string]any `json:"actor"`
	TaskID    *string        `json:"taskId,omitempty"`
	Note      *string        `json:"note,omitempty"`
	Ts        time.Time      `json:"ts"`
}

type TaskRollup struct {
	TaskID             string         `json:"taskId"`
	TenantID           string         `json:"tenantId"`
	Batches            int            `json:"batches"`
	RejectedBatches    int            `json:"rejectedBatches"`
	AssetsTouched      int            `json:"assetsTouched"`
	FindingsProduced   int            `json:"findingsProduced"`
	FindingsBySeverity map[string]any `json:"findingsBySeverity"`
	FirstActivity      *time.Time     `json:"firstActivity,omitempty"`
	LastActivity       *time.Time     `json:"lastActivity,omitempty"`
}
