/**
 * Compiled-in static tables (doc 07 §3.2). The intel bundle overlays the TLD
 * risk table (`tldRiskTable`); the shortener table is deliberately static —
 * live expansion is explicitly out of scope (§1: "no live URL unshortening").
 */

/** Known URL shorteners (registered domains). Membership is signal-weight only. */
export const KNOWN_SHORTENERS: ReadonlySet<string> = new Set([
  "bit.ly", "tinyurl.com", "t.co", "goo.gl", "ow.ly", "is.gd", "buff.ly",
  "rebrand.ly", "cutt.ly", "shorturl.at", "tiny.cc", "rb.gy", "short.io",
  "bl.ink", "soo.gd", "s.id", "clck.ru", "v.gd", "qr.ae", "lnkd.in",
]);

/**
 * Default ranked TLD risk table (tld → 0–100 risk weight). The bundle's
 * `tldRiskTable` replaces/extends this (doc 07 §4.4 example: {"zip": 20}).
 */
export const DEFAULT_TLD_RISK: Readonly<Record<string, number>> = Object.freeze({
  zip: 20,
  mov: 20,
  top: 15,
  xyz: 15,
  click: 20,
  link: 10,
  live: 5,
  buzz: 15,
  quest: 15,
  cam: 15,
  rest: 15,
  monster: 15,
  beauty: 10,
  hair: 10,
  skin: 10,
  makeup: 10,
  bond: 10,
  cfd: 15,
  autos: 5,
  boats: 5,
  motorcycles: 5,
  gdn: 20,
  loan: 25,
  win: 20,
  bid: 20,
  stream: 15,
  download: 20,
  review: 10,
  date: 20,
  men: 20,
  work: 15,
  party: 15,
  science: 20,
  faith: 15,
  cricket: 15,
  account: 15,
  webcam: 20,
  racing: 15,
  country: 10,
  kim: 10,
  vip: 15,
  online: 10,
  site: 10,
  website: 10,
  space: 10,
  tech: 5,
  store: 5,
  shop: 5,
  club: 10,
  fun: 10,
  host: 10,
  press: 10,
  pw: 25,
  tk: 30,
  ml: 30,
  ga: 30,
  cf: 30,
  gq: 30,
  cc: 10,
  su: 15,
  cn: 10,
  ru: 10,
  biz: 10,
  info: 10,
  icu: 20,
  lol: 10,
  pics: 10,
  mom: 10,
  lat: 5,
  sbs: 20,
  uno: 10,
  feedback: 10,
  zones: 10,
  yachts: 5,
  email: 10,
  support: 15,
  help: 10,
});
